"""initial schema

Revision ID: b03d8482acff
Revises:
Create Date: 2026-05-15 18:00:50.143022

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b03d8482acff"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clubs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("creation_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_clubs_id"), "clubs", ["id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("password", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("email_confirmed", sa.Integer(), nullable=False),
        sa.Column("email_confirmation_token", sa.String(), nullable=True),
        sa.Column("email_confirmation_expires", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "club_invitations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("club_id", sa.Integer(), nullable=True),
        sa.Column("invited_user_id", sa.Integer(), nullable=True),
        sa.Column("inviter_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("creation_date", sa.DateTime(), nullable=True),
        sa.Column("expiration_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["club_id"],
            ["clubs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["invited_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["inviter_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_club_invitations_id"), "club_invitations", ["id"], unique=False
    )
    op.create_table(
        "club_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("club_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("role", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["club_id"],
            ["clubs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_club_users_id"), "club_users", ["id"], unique=False)
    op.create_table(
        "password_reset_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("token", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("used", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_password_reset_tokens_id"),
        "password_reset_tokens",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_password_reset_tokens_token"),
        "password_reset_tokens",
        ["token"],
        unique=True,
    )
    op.create_table(
        "players",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("velocidad", sa.Integer(), nullable=True),
        sa.Column("resistencia", sa.Integer(), nullable=True),
        sa.Column("control", sa.Integer(), nullable=True),
        sa.Column("pases", sa.Integer(), nullable=True),
        sa.Column("tiro", sa.Integer(), nullable=True),
        sa.Column("defensa", sa.Integer(), nullable=True),
        sa.Column("habilidad_arquero", sa.Integer(), nullable=True),
        sa.Column("fuerza_cuerpo", sa.Integer(), nullable=True),
        sa.Column("vision", sa.Integer(), nullable=True),
        sa.Column("photo_data", sa.Text(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("club_id", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("last_modified_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["club_id"],
            ["clubs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["last_modified_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_players_id"), "players", ["id"], unique=False)
    op.create_index(op.f("ix_players_name"), "players", ["name"], unique=False)
    op.create_table(
        "players_v2",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("velocidad", sa.Integer(), nullable=True),
        sa.Column("resistencia", sa.Integer(), nullable=True),
        sa.Column("control", sa.Integer(), nullable=True),
        sa.Column("pases", sa.Integer(), nullable=True),
        sa.Column("tiro", sa.Integer(), nullable=True),
        sa.Column("defensa", sa.Integer(), nullable=True),
        sa.Column("habilidad_arquero", sa.Integer(), nullable=True),
        sa.Column("fuerza_cuerpo", sa.Integer(), nullable=True),
        sa.Column("vision", sa.Integer(), nullable=True),
        sa.Column("photo_data", sa.Text(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("club_id", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("last_modified_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["club_id"],
            ["clubs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["last_modified_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_players_v2_id"), "players_v2", ["id"], unique=False)
    op.create_index(op.f("ix_players_v2_name"), "players_v2", ["name"], unique=False)
    op.create_table(
        "skill_votes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=True),
        sa.Column("voter_id", sa.Integer(), nullable=True),
        sa.Column("velocidad", sa.Integer(), nullable=True),
        sa.Column("resistencia", sa.Integer(), nullable=True),
        sa.Column("control", sa.Integer(), nullable=True),
        sa.Column("pases", sa.Integer(), nullable=True),
        sa.Column("tiro", sa.Integer(), nullable=True),
        sa.Column("defensa", sa.Integer(), nullable=True),
        sa.Column("habilidad_arquero", sa.Integer(), nullable=True),
        sa.Column("fuerza_cuerpo", sa.Integer(), nullable=True),
        sa.Column("vision", sa.Integer(), nullable=True),
        sa.Column("vote_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.ForeignKeyConstraint(
            ["voter_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_skill_votes_id"), "skill_votes", ["id"], unique=False)
    op.create_table(
        "skill_votes_v2",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=True),
        sa.Column("voter_id", sa.Integer(), nullable=True),
        sa.Column("velocidad", sa.Integer(), nullable=True),
        sa.Column("resistencia", sa.Integer(), nullable=True),
        sa.Column("control", sa.Integer(), nullable=True),
        sa.Column("pases", sa.Integer(), nullable=True),
        sa.Column("tiro", sa.Integer(), nullable=True),
        sa.Column("defensa", sa.Integer(), nullable=True),
        sa.Column("habilidad_arquero", sa.Integer(), nullable=True),
        sa.Column("fuerza_cuerpo", sa.Integer(), nullable=True),
        sa.Column("vision", sa.Integer(), nullable=True),
        sa.Column("vote_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players_v2.id"],
        ),
        sa.ForeignKeyConstraint(
            ["voter_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_skill_votes_v2_id"), "skill_votes_v2", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_skill_votes_v2_id"), table_name="skill_votes_v2")
    op.drop_table("skill_votes_v2")
    op.drop_index(op.f("ix_skill_votes_id"), table_name="skill_votes")
    op.drop_table("skill_votes")
    op.drop_index(op.f("ix_players_v2_name"), table_name="players_v2")
    op.drop_index(op.f("ix_players_v2_id"), table_name="players_v2")
    op.drop_table("players_v2")
    op.drop_index(op.f("ix_players_name"), table_name="players")
    op.drop_index(op.f("ix_players_id"), table_name="players")
    op.drop_table("players")
    op.drop_index(
        op.f("ix_password_reset_tokens_token"), table_name="password_reset_tokens"
    )
    op.drop_index(
        op.f("ix_password_reset_tokens_id"), table_name="password_reset_tokens"
    )
    op.drop_table("password_reset_tokens")
    op.drop_index(op.f("ix_club_users_id"), table_name="club_users")
    op.drop_table("club_users")
    op.drop_index(op.f("ix_club_invitations_id"), table_name="club_invitations")
    op.drop_table("club_invitations")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_clubs_id"), table_name="clubs")
    op.drop_table("clubs")
    # ### end Alembic commands ###
