"""add matches tables

Revision ID: c6a9f1b0c2d3
Revises: 3748d7264451
Create Date: 2026-05-19 00:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c6a9f1b0c2d3"
down_revision: Union[str, Sequence[str], None] = "3748d7264451"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "matches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("club_id", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("played_at", sa.DateTime(), nullable=False),
        sa.Column("team_a_score", sa.Integer(), nullable=False),
        sa.Column("team_b_score", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["club_id"],
            ["clubs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_matches_id"), "matches", ["id"], unique=False)
    op.create_table(
        "match_players",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("player_v1_id", sa.Integer(), nullable=True),
        sa.Column("player_v2_id", sa.Integer(), nullable=True),
        sa.Column("team", sa.String(), nullable=False),
        sa.Column("result", sa.String(), nullable=False),
        sa.CheckConstraint(
            "(player_v1_id IS NOT NULL AND player_v2_id IS NULL) OR "
            "(player_v1_id IS NULL AND player_v2_id IS NOT NULL)",
            name="ck_match_players_one_player",
        ),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_v1_id"],
            ["players.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_v2_id"],
            ["players_v2.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_match_players_id"), "match_players", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_match_players_id"), table_name="match_players")
    op.drop_table("match_players")
    op.drop_index(op.f("ix_matches_id"), table_name="matches")
    op.drop_table("matches")
    # ### end Alembic commands ###
